name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: c-hive/gha-npm-cache@v1
      - run: npm ci
      - run: npm test
  build:
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: c-hive/gha-npm-cache@v1
      # - uses: samuelmeuli/action-snapcraft@v1
      #   if: startsWith(matrix.os, 'ubuntu')
      #   with:
      #     snapcraft_token: ${{ secrets.snapcraft_token }}
      - uses: samuelmeuli/action-electron-builder@v1
        with:
          args: "--x64 --arm64"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          mac_certs: ${{ secrets.CSC_LINK }}
          mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
          
